### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by Daniel15** [ClouDNS/cloudns-php-sdk#1]
Is this SDK available to install via Composer?

**Comment by agcdns** [comment]
Hello,
At the moment the SDK is not available to install via Composer. However, we have it in our plans to do so and will keep you updated once it is available.

**Comment by yswery** [comment]
+1 for this please

**Comment by MACscr** [comment]
Still not available? Can you be done pretty quickly. Would like to see some effort towards this.

**Comment by cardentey** [comment]
+1 for this please

**Comment by boyanpeychev** [comment]
Composer is added 7 months ago. Sorry for the late update.
