### ISSUE TITLE
'status' field missing in example

### ISSUE THREAD

**Issue by KrisLowet** [ClouDNS/cloudns-php-sdk#5]
In the documentation about 'dnsModifyRecord', the 'status' field is missing in the example.

This example:
`$exampleVar->dnsModifyRecord("domain.tld", "recordID", "host", "record", ttl, priority, weight, port, frame, "frame-title", "frame-keywords", "frame-description", save-path, redirect-type, "mail", "txt", algorithm, fptype, geodns-location, caa-flag, "caa-type", "caa-value");`

Has to be:
`$exampleVar->dnsModifyRecord("domain.tld", "recordID", "host", "record", ttl, priority, weight, port, frame, "frame-title", "frame-keywords", "frame-description", save-path, redirect-type, "mail", "txt", algorithm, fptype, status, geodns-location, caa-flag, "caa-type", "caa-value");`

**Comment by agcdns** [comment]
Hello,
Thank you for the feedback. The missing field was added to the example.
